var readline = require("readline-sync");
// program where the user has to guess a number generated by a program

function guessNumber() {

    // generating a pseudo random integer from 10 to 100
    var random = Math.floor(Math.random() * 91) + 10;

    // take input from the user
    let number = parseInt(readline.question('Guess a number from 1 to 10: '));

    // take the input until the guess is correct
    while(number !== random) {
        console.log("Correct number:" + random);
        number = parseInt(readline.question('Guess a number from 1 to 10: '));
        // generating a random integer from 1 to 10
        random = Math.floor(Math.random() * 10) + 1;
    }

    // check if the guess is correct
    if(number == random) {
        console.log('You guessed the correct number.');
    }

  }

// call the function
guessNumber();